language: python
python:
- 3.7

install:
 - pip install -r docs/requirements.txt

script:
 - bash test.sh
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
   email:
     - magnus@genesilico.pl
